// AUTO-GENERATED from the spreadsheet's Field Map tab (4FINGERS_POC_Spec_and_Build_Tracker.xlsx).
// Do not hand-edit field data here; regenerate from the spreadsheet if it changes,
// and record any coordinate calibration in docs/SESSION_LOG.md (see docs/FIELD_MAP.md).

import type { FieldMeta } from "./types";

export const FIELD_MAP: readonly FieldMeta[] = [
  {
    id: "position_applied_for",
    page: 1,
    section: "Application",
    label: "Position applied for",
    type: "text",
    row: undefined,
    owner: "candidate",
    pocRequired: "required",
    sources: { resume: "Possible", linkedin: "Possible", manual: "Yes" },
    exportable: true,
    overlay: { x: 88, y: 86, w: 400, h: 13 },
    validation: "1-80 chars",
    conditional: undefined,
    notes: "Single line inside top box",
  },
  {
    id: "full_name",
    page: 1,
    section: "Personal",
    label: "Full name; surname underlined in source instruction",
    type: "text",
    row: undefined,
    owner: "candidate",
    pocRequired: "required",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 89, y: 137, w: 250, h: 24 },
    validation: "1-120 chars",
    conditional: undefined,
    notes: "POC cannot reliably underline surname unless surname is captured separately",
  },
  {
    id: "identity_number",
    page: 1,
    section: "Personal",
    label: "NRIC / FIN / Passport No.",
    type: "identifier",
    row: undefined,
    owner: "candidate",
    pocRequired: "required",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 360, y: 137, w: 120, h: 16 },
    validation: "Preserve as text",
    conditional: undefined,
    notes: "Sensitive; never infer from resume",
  },
  {
    id: "address",
    page: 1,
    section: "Personal",
    label: "Address",
    type: "multiline",
    row: undefined,
    owner: "candidate",
    pocRequired: "required",
    sources: { resume: "Possible", linkedin: "Possible", manual: "Yes" },
    exportable: true,
    overlay: { x: 89, y: 179, w: 250, h: 30 },
    validation: "1-250 chars",
    conditional: undefined,
    notes: "Wrap to two lines",
  },
  {
    id: "telephone_home",
    page: 1,
    section: "Personal",
    label: "Telephone - Home",
    type: "text",
    row: undefined,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Possible", linkedin: "Possible", manual: "Yes" },
    exportable: true,
    overlay: { x: 390, y: 179, w: 95, h: 13 },
    validation: "Phone-like text",
    conditional: undefined,
    notes: "Preserve leading + and zeros",
  },
  {
    id: "telephone_mobile",
    page: 1,
    section: "Personal",
    label: "Telephone - Mobile",
    type: "text",
    row: undefined,
    owner: "candidate",
    pocRequired: "required",
    sources: { resume: "Possible", linkedin: "Possible", manual: "Yes" },
    exportable: true,
    overlay: { x: 390, y: 218, w: 95, h: 13 },
    validation: "Phone-like text",
    conditional: undefined,
    notes: "Preserve leading + and zeros",
  },
  {
    id: "email",
    page: 1,
    section: "Personal",
    label: "Email address",
    type: "email",
    row: undefined,
    owner: "candidate",
    pocRequired: "required",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 89, y: 219, w: 250, h: 13 },
    validation: "Valid email",
    conditional: undefined,
    notes: "Shrink font if long",
  },
  {
    id: "citizenship",
    page: 1,
    section: "Personal",
    label: "Citizenship",
    type: "text",
    row: undefined,
    owner: "candidate",
    pocRequired: "required",
    sources: { resume: "Possible", linkedin: "Possible", manual: "Yes" },
    exportable: true,
    overlay: { x: 89, y: 258, w: 250, h: 13 },
    validation: "1-80 chars",
    conditional: undefined,
    notes: "Do not infer legal status from nationality",
  },
  {
    id: "legal_right_to_work_sg",
    page: 1,
    section: "Personal",
    label: "Legal rights to work in Singapore",
    type: "text",
    row: undefined,
    owner: "candidate",
    pocRequired: "required",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 390, y: 255, w: 95, h: 24 },
    validation: "1-120 chars",
    conditional: undefined,
    notes: "Manual confirmation only",
  },
  {
    id: "education_1_institution",
    page: 1,
    section: "Education",
    label: "School / College / University",
    type: "text",
    row: 1,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 88, y: 299, w: 170, h: 14 },
    validation: "0-120 chars",
    conditional: undefined,
    notes: "Row order preserved",
  },
  {
    id: "education_1_from",
    page: 1,
    section: "Education",
    label: "From",
    type: "date_or_year",
    row: 1,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 270, y: 299, w: 50, h: 14 },
    validation: "Date or year",
    conditional: undefined,
    notes: "Display compactly",
  },
  {
    id: "education_1_to",
    page: 1,
    section: "Education",
    label: "To",
    type: "date_or_year",
    row: 1,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 331, y: 299, w: 50, h: 14 },
    validation: "Date, year, or Present",
    conditional: undefined,
    notes: "Display compactly",
  },
  {
    id: "education_1_standard",
    page: 1,
    section: "Education",
    label: "Standard achieved",
    type: "text",
    row: 1,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 392, y: 299, w: 95, h: 14 },
    validation: "0-100 chars",
    conditional: undefined,
    notes: "Qualification / result",
  },
  {
    id: "education_2_institution",
    page: 1,
    section: "Education",
    label: "School / College / University",
    type: "text",
    row: 2,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 88, y: 319, w: 170, h: 14 },
    validation: "0-120 chars",
    conditional: undefined,
    notes: "Row order preserved",
  },
  {
    id: "education_2_from",
    page: 1,
    section: "Education",
    label: "From",
    type: "date_or_year",
    row: 2,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 270, y: 319, w: 50, h: 14 },
    validation: "Date or year",
    conditional: undefined,
    notes: "Display compactly",
  },
  {
    id: "education_2_to",
    page: 1,
    section: "Education",
    label: "To",
    type: "date_or_year",
    row: 2,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 331, y: 319, w: 50, h: 14 },
    validation: "Date, year, or Present",
    conditional: undefined,
    notes: "Display compactly",
  },
  {
    id: "education_2_standard",
    page: 1,
    section: "Education",
    label: "Standard achieved",
    type: "text",
    row: 2,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 392, y: 319, w: 95, h: 14 },
    validation: "0-100 chars",
    conditional: undefined,
    notes: "Qualification / result",
  },
  {
    id: "education_3_institution",
    page: 1,
    section: "Education",
    label: "School / College / University",
    type: "text",
    row: 3,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 88, y: 339, w: 170, h: 14 },
    validation: "0-120 chars",
    conditional: undefined,
    notes: "Row order preserved",
  },
  {
    id: "education_3_from",
    page: 1,
    section: "Education",
    label: "From",
    type: "date_or_year",
    row: 3,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 270, y: 339, w: 50, h: 14 },
    validation: "Date or year",
    conditional: undefined,
    notes: "Display compactly",
  },
  {
    id: "education_3_to",
    page: 1,
    section: "Education",
    label: "To",
    type: "date_or_year",
    row: 3,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 331, y: 339, w: 50, h: 14 },
    validation: "Date, year, or Present",
    conditional: undefined,
    notes: "Display compactly",
  },
  {
    id: "education_3_standard",
    page: 1,
    section: "Education",
    label: "Standard achieved",
    type: "text",
    row: 3,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 392, y: 339, w: 95, h: 14 },
    validation: "0-100 chars",
    conditional: undefined,
    notes: "Qualification / result",
  },
  {
    id: "employment_1_from",
    page: 1,
    section: "Employment",
    label: "From (dd/mm/yy)",
    type: "date",
    row: 1,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 86, y: 408, w: 34, h: 14 },
    validation: "Date",
    conditional: undefined,
    notes: "Current job first",
  },
  {
    id: "employment_1_to",
    page: 1,
    section: "Employment",
    label: "To (dd/mm/yy)",
    type: "date_or_present",
    row: 1,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 125, y: 408, w: 34, h: 14 },
    validation: "Date or Present",
    conditional: undefined,
    notes: "Current job may be Present",
  },
  {
    id: "employment_1_employer",
    page: 1,
    section: "Employment",
    label: "Employer",
    type: "text",
    row: 1,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 165, y: 408, w: 86, h: 14 },
    validation: "0-120 chars",
    conditional: undefined,
    notes: "Shrink if necessary",
  },
  {
    id: "employment_1_superior",
    page: 1,
    section: "Employment",
    label: "Name of superior",
    type: "text",
    row: 1,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Possible", linkedin: "Possible", manual: "Yes" },
    exportable: true,
    overlay: { x: 258, y: 408, w: 49, h: 14 },
    validation: "0-100 chars",
    conditional: undefined,
    notes: "Often missing from resume",
  },
  {
    id: "employment_1_position",
    page: 1,
    section: "Employment",
    label: "Position last-held",
    type: "text",
    row: 1,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 313, y: 408, w: 48, h: 14 },
    validation: "0-100 chars",
    conditional: undefined,
    notes: "Last-held title",
  },
  {
    id: "employment_1_last_salary",
    page: 1,
    section: "Employment",
    label: "Last drawn salary",
    type: "text",
    row: 1,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 367, y: 408, w: 40, h: 14 },
    validation: "Currency text",
    conditional: undefined,
    notes: "Never infer",
  },
  {
    id: "employment_1_reason_leaving",
    page: 1,
    section: "Employment",
    label: "Reason for leaving",
    type: "text",
    row: 1,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 414, y: 408, w: 72, h: 14 },
    validation: "0-120 chars",
    conditional: undefined,
    notes: "Manual confirmation",
  },
  {
    id: "employment_2_from",
    page: 1,
    section: "Employment",
    label: "From (dd/mm/yy)",
    type: "date",
    row: 2,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 86, y: 428, w: 34, h: 14 },
    validation: "Date",
    conditional: undefined,
    notes: "Current job first",
  },
  {
    id: "employment_2_to",
    page: 1,
    section: "Employment",
    label: "To (dd/mm/yy)",
    type: "date_or_present",
    row: 2,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 125, y: 428, w: 34, h: 14 },
    validation: "Date or Present",
    conditional: undefined,
    notes: "Current job may be Present",
  },
  {
    id: "employment_2_employer",
    page: 1,
    section: "Employment",
    label: "Employer",
    type: "text",
    row: 2,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 165, y: 428, w: 86, h: 14 },
    validation: "0-120 chars",
    conditional: undefined,
    notes: "Shrink if necessary",
  },
  {
    id: "employment_2_superior",
    page: 1,
    section: "Employment",
    label: "Name of superior",
    type: "text",
    row: 2,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Possible", linkedin: "Possible", manual: "Yes" },
    exportable: true,
    overlay: { x: 258, y: 428, w: 49, h: 14 },
    validation: "0-100 chars",
    conditional: undefined,
    notes: "Often missing from resume",
  },
  {
    id: "employment_2_position",
    page: 1,
    section: "Employment",
    label: "Position last-held",
    type: "text",
    row: 2,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 313, y: 428, w: 48, h: 14 },
    validation: "0-100 chars",
    conditional: undefined,
    notes: "Last-held title",
  },
  {
    id: "employment_2_last_salary",
    page: 1,
    section: "Employment",
    label: "Last drawn salary",
    type: "text",
    row: 2,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 367, y: 428, w: 40, h: 14 },
    validation: "Currency text",
    conditional: undefined,
    notes: "Never infer",
  },
  {
    id: "employment_2_reason_leaving",
    page: 1,
    section: "Employment",
    label: "Reason for leaving",
    type: "text",
    row: 2,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 414, y: 428, w: 72, h: 14 },
    validation: "0-120 chars",
    conditional: undefined,
    notes: "Manual confirmation",
  },
  {
    id: "employment_3_from",
    page: 1,
    section: "Employment",
    label: "From (dd/mm/yy)",
    type: "date",
    row: 3,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 86, y: 448, w: 34, h: 14 },
    validation: "Date",
    conditional: undefined,
    notes: "Current job first",
  },
  {
    id: "employment_3_to",
    page: 1,
    section: "Employment",
    label: "To (dd/mm/yy)",
    type: "date_or_present",
    row: 3,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 125, y: 448, w: 34, h: 14 },
    validation: "Date or Present",
    conditional: undefined,
    notes: "Current job may be Present",
  },
  {
    id: "employment_3_employer",
    page: 1,
    section: "Employment",
    label: "Employer",
    type: "text",
    row: 3,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 165, y: 448, w: 86, h: 14 },
    validation: "0-120 chars",
    conditional: undefined,
    notes: "Shrink if necessary",
  },
  {
    id: "employment_3_superior",
    page: 1,
    section: "Employment",
    label: "Name of superior",
    type: "text",
    row: 3,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Possible", linkedin: "Possible", manual: "Yes" },
    exportable: true,
    overlay: { x: 258, y: 448, w: 49, h: 14 },
    validation: "0-100 chars",
    conditional: undefined,
    notes: "Often missing from resume",
  },
  {
    id: "employment_3_position",
    page: 1,
    section: "Employment",
    label: "Position last-held",
    type: "text",
    row: 3,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Yes", linkedin: "Yes", manual: "Yes" },
    exportable: true,
    overlay: { x: 313, y: 448, w: 48, h: 14 },
    validation: "0-100 chars",
    conditional: undefined,
    notes: "Last-held title",
  },
  {
    id: "employment_3_last_salary",
    page: 1,
    section: "Employment",
    label: "Last drawn salary",
    type: "text",
    row: 3,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 367, y: 448, w: 40, h: 14 },
    validation: "Currency text",
    conditional: undefined,
    notes: "Never infer",
  },
  {
    id: "employment_3_reason_leaving",
    page: 1,
    section: "Employment",
    label: "Reason for leaving",
    type: "text",
    row: 3,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 414, y: 448, w: 72, h: 14 },
    validation: "0-120 chars",
    conditional: undefined,
    notes: "Manual confirmation",
  },
  {
    id: "reference_1_name",
    page: 1,
    section: "References",
    label: "Name",
    type: "text",
    row: 1,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 88, y: 507, w: 105, h: 14 },
    validation: "0-120 chars",
    conditional: undefined,
    notes: "Professional ex-immediate superior preferred",
  },
  {
    id: "reference_1_telephone",
    page: 1,
    section: "References",
    label: "Tel No.",
    type: "text",
    row: 1,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 201, y: 507, w: 70, h: 14 },
    validation: "Phone-like text",
    conditional: undefined,
    notes: "Preserve leading + and zeros",
  },
  {
    id: "reference_1_profession",
    page: 1,
    section: "References",
    label: "Profession",
    type: "text",
    row: 1,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 279, y: 507, w: 92, h: 14 },
    validation: "0-100 chars",
    conditional: undefined,
    notes: "Could contain role/company",
  },
  {
    id: "reference_1_years_known",
    page: 1,
    section: "References",
    label: "Years Known",
    type: "text",
    row: 1,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 379, y: 507, w: 105, h: 14 },
    validation: "0-40 chars",
    conditional: undefined,
    notes: "Text supports ranges",
  },
  {
    id: "reference_2_name",
    page: 1,
    section: "References",
    label: "Name",
    type: "text",
    row: 2,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 88, y: 527, w: 105, h: 14 },
    validation: "0-120 chars",
    conditional: undefined,
    notes: "Professional ex-immediate superior preferred",
  },
  {
    id: "reference_2_telephone",
    page: 1,
    section: "References",
    label: "Tel No.",
    type: "text",
    row: 2,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 201, y: 527, w: 70, h: 14 },
    validation: "Phone-like text",
    conditional: undefined,
    notes: "Preserve leading + and zeros",
  },
  {
    id: "reference_2_profession",
    page: 1,
    section: "References",
    label: "Profession",
    type: "text",
    row: 2,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 279, y: 527, w: 92, h: 14 },
    validation: "0-100 chars",
    conditional: undefined,
    notes: "Could contain role/company",
  },
  {
    id: "reference_2_years_known",
    page: 1,
    section: "References",
    label: "Years Known",
    type: "text",
    row: 2,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 379, y: 527, w: 105, h: 14 },
    validation: "0-40 chars",
    conditional: undefined,
    notes: "Text supports ranges",
  },
  {
    id: "languages_spoken",
    page: 1,
    section: "Languages",
    label: "Spoken",
    type: "text_list",
    row: undefined,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Possible", linkedin: "Possible", manual: "Yes" },
    exportable: true,
    overlay: { x: 89, y: 571, w: 190, h: 14 },
    validation: "Comma-separated or list",
    conditional: undefined,
    notes: "Free text in source",
  },
  {
    id: "languages_written",
    page: 1,
    section: "Languages",
    label: "Written",
    type: "text_list",
    row: undefined,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Possible", linkedin: "Possible", manual: "Yes" },
    exportable: true,
    overlay: { x: 300, y: 571, w: 185, h: 14 },
    validation: "Comma-separated or list",
    conditional: undefined,
    notes: "Free text in source",
  },
  {
    id: "driving_licence_answer",
    page: 2,
    section: "Other information",
    label: "Driving licence",
    type: "yes_no",
    row: undefined,
    owner: "candidate",
    pocRequired: "required",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 340, y: 35, w: 35, h: 14 },
    validation: "Yes or No",
    conditional: undefined,
    notes: "Draw mark beside selected choice",
  },
  {
    id: "driving_licence_details",
    page: 2,
    section: "Other information",
    label: "Driving licence - details",
    type: "text",
    row: undefined,
    owner: "candidate",
    pocRequired: "conditional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 388, y: 48, w: 95, h: 13 },
    validation: "Required when Yes",
    conditional: "driving_licence_answer = Yes",
    notes: "Use available detail line / right-side space",
  },
  {
    id: "criminal_charge_answer",
    page: 2,
    section: "Other information",
    label: "Charged / convicted in any country",
    type: "yes_no",
    row: undefined,
    owner: "candidate",
    pocRequired: "required",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 340, y: 63, w: 35, h: 14 },
    validation: "Yes or No",
    conditional: undefined,
    notes: "Draw mark beside selected choice",
  },
  {
    id: "criminal_charge_details",
    page: 2,
    section: "Other information",
    label: "Charged / convicted in any country - details",
    type: "text",
    row: undefined,
    owner: "candidate",
    pocRequired: "conditional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 388, y: 76, w: 95, h: 13 },
    validation: "Required when Yes",
    conditional: "criminal_charge_answer = Yes",
    notes: "Use available detail line / right-side space",
  },
  {
    id: "employment_discipline_answer",
    page: 2,
    section: "Other information",
    label: "Dismissed / discharged / suspended",
    type: "yes_no",
    row: undefined,
    owner: "candidate",
    pocRequired: "required",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 340, y: 91, w: 35, h: 14 },
    validation: "Yes or No",
    conditional: undefined,
    notes: "Draw mark beside selected choice",
  },
  {
    id: "employment_discipline_details",
    page: 2,
    section: "Other information",
    label: "Dismissed / discharged / suspended - details",
    type: "text",
    row: undefined,
    owner: "candidate",
    pocRequired: "conditional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 388, y: 104, w: 95, h: 13 },
    validation: "Required when Yes",
    conditional: "employment_discipline_answer = Yes",
    notes: "Use available detail line / right-side space",
  },
  {
    id: "medical_impact_answer",
    page: 2,
    section: "Other information",
    label: "Medical condition affecting work",
    type: "yes_no",
    row: undefined,
    owner: "candidate",
    pocRequired: "required",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 340, y: 119, w: 35, h: 14 },
    validation: "Yes or No",
    conditional: undefined,
    notes: "Draw mark beside selected choice",
  },
  {
    id: "medical_impact_details",
    page: 2,
    section: "Other information",
    label: "Medical condition affecting work - details",
    type: "text",
    row: undefined,
    owner: "candidate",
    pocRequired: "conditional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 388, y: 132, w: 95, h: 13 },
    validation: "Required when Yes",
    conditional: "medical_impact_answer = Yes",
    notes: "Use available detail line / right-side space",
  },
  {
    id: "bankruptcy_answer",
    page: 2,
    section: "Other information",
    label: "Declared bankrupt",
    type: "yes_no",
    row: undefined,
    owner: "candidate",
    pocRequired: "required",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 340, y: 147, w: 35, h: 14 },
    validation: "Yes or No",
    conditional: undefined,
    notes: "Draw mark beside selected choice",
  },
  {
    id: "bankruptcy_details",
    page: 2,
    section: "Other information",
    label: "Declared bankrupt - details",
    type: "text",
    row: undefined,
    owner: "candidate",
    pocRequired: "conditional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 388, y: 160, w: 95, h: 13 },
    validation: "Required when Yes",
    conditional: "bankruptcy_answer = Yes",
    notes: "Use available detail line / right-side space",
  },
  {
    id: "company_contact_answer",
    page: 2,
    section: "Other information",
    label: "Relatives / friends in this Company",
    type: "yes_no",
    row: undefined,
    owner: "candidate",
    pocRequired: "required",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 340, y: 176, w: 35, h: 14 },
    validation: "Yes or No",
    conditional: undefined,
    notes: "Draw mark beside selected choice",
  },
  {
    id: "company_contact_name",
    page: 2,
    section: "Other information",
    label: "Name of 4FINGERS contact",
    type: "text",
    row: undefined,
    owner: "candidate",
    pocRequired: "conditional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 395, y: 199, w: 90, h: 13 },
    validation: "Required when Yes",
    conditional: "company_contact_answer = Yes",
    notes: "Named as 4Fingers Rebel in source",
  },
  {
    id: "company_contact_department",
    page: 2,
    section: "Other information",
    label: "Department contact works at",
    type: "text",
    row: undefined,
    owner: "candidate",
    pocRequired: "conditional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 436, y: 215, w: 49, h: 13 },
    validation: "Required when Yes",
    conditional: "company_contact_answer = Yes",
    notes: "Small overlay area",
  },
  {
    id: "vacancy_source_friend",
    page: 2,
    section: "Vacancy source",
    label: "Through friend / relatives",
    type: "boolean",
    row: undefined,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Possible", linkedin: "Possible", manual: "Yes" },
    exportable: true,
    overlay: { x: 89, y: 296, w: 10, h: 10 },
    validation: "True/False",
    conditional: undefined,
    notes: "Checkbox",
  },
  {
    id: "vacancy_source_job_portal",
    page: 2,
    section: "Vacancy source",
    label: "Job portal selected",
    type: "boolean",
    row: undefined,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Possible", linkedin: "Possible", manual: "Yes" },
    exportable: true,
    overlay: { x: 89, y: 311, w: 10, h: 10 },
    validation: "True/False",
    conditional: undefined,
    notes: "Checkbox",
  },
  {
    id: "vacancy_source_job_portal_name",
    page: 2,
    section: "Vacancy source",
    label: "Job portal name",
    type: "text",
    row: undefined,
    owner: "candidate",
    pocRequired: "conditional",
    sources: { resume: "Possible", linkedin: "Possible", manual: "Yes" },
    exportable: true,
    overlay: { x: 143, y: 311, w: 105, h: 13 },
    validation: "Required if selected",
    conditional: "vacancy_source_job_portal = True",
    notes: "Write on line",
  },
  {
    id: "vacancy_source_other",
    page: 2,
    section: "Vacancy source",
    label: "Other selected",
    type: "boolean",
    row: undefined,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 89, y: 326, w: 10, h: 10 },
    validation: "True/False",
    conditional: undefined,
    notes: "Checkbox",
  },
  {
    id: "vacancy_source_other_details",
    page: 2,
    section: "Vacancy source",
    label: "Other source details",
    type: "text",
    row: undefined,
    owner: "candidate",
    pocRequired: "conditional",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 197, y: 326, w: 102, h: 13 },
    validation: "Required if selected",
    conditional: "vacancy_source_other = True",
    notes: "Write on line",
  },
  {
    id: "expected_salary",
    page: 2,
    section: "Application",
    label: "Expected Salary",
    type: "text",
    row: undefined,
    owner: "candidate",
    pocRequired: "required",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 150, y: 344, w: 330, h: 13 },
    validation: "Currency text",
    conditional: undefined,
    notes: "Never infer",
  },
  {
    id: "termination_notice",
    page: 2,
    section: "Application",
    label: "Termination Notice for present job",
    type: "text",
    row: undefined,
    owner: "candidate",
    pocRequired: "required",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 205, y: 362, w: 275, h: 13 },
    validation: "0-100 chars",
    conditional: undefined,
    notes: "Manual confirmation",
  },
  {
    id: "supporting_information",
    page: 2,
    section: "Application",
    label: "Other information supporting application",
    type: "multiline",
    row: undefined,
    owner: "candidate",
    pocRequired: "optional",
    sources: { resume: "Possible", linkedin: "Possible", manual: "Yes" },
    exportable: true,
    overlay: { x: 235, y: 380, w: 245, h: 18 },
    validation: "0-500 chars",
    conditional: undefined,
    notes: "Wrap / shrink",
  },
  {
    id: "declaration_accepted",
    page: 2,
    section: "Declaration",
    label: "Declaration accepted",
    type: "boolean",
    row: undefined,
    owner: "candidate",
    pocRequired: "required",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: undefined,
    validation: "Must be true for final PDF",
    conditional: undefined,
    notes: "Consent state is exported but not drawn",
  },
  {
    id: "declaration_date",
    page: 2,
    section: "Declaration",
    label: "Date",
    type: "date",
    row: undefined,
    owner: "candidate",
    pocRequired: "required",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    exportable: true,
    overlay: { x: 56, y: 487, w: 110, h: 14 },
    validation: "Date",
    conditional: "declaration_accepted = True",
    notes: "Draw beside Date label",
  },
  {
    id: "applicant_signature",
    page: 2,
    section: "Declaration",
    label: "Signature of applicant",
    type: "signature",
    row: undefined,
    owner: "candidate",
    pocRequired: "required",
    sources: { resume: "No", linkedin: "No", manual: "Yes" },
    // Hand-corrected (S08): the spreadsheet's CSV/XLSX column says
    // "Metadata only", not "Yes" — the codegen's exportable=(col==="Yes")
    // rule mapped that to false, silently dropping this field from every
    // export. "Metadata only" means it should still be exported, just
    // never as raw signature bytes (see rowData.ts's signature handling,
    // which exports only kind/capturedAt via toSignatureExportMetadata).
    exportable: true,
    overlay: { x: 250, y: 474, w: 225, h: 25 },
    validation: "Image or typed POC signature",
    conditional: "declaration_accepted = True",
    notes: "Do not place signature bytes in CSV/XLSX",
  },
  {
    id: "official_date",
    page: 2,
    section: "FOR OFFICIAL USE ONLY",
    label: "Date",
    type: "date",
    row: undefined,
    owner: "hr",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "No" },
    exportable: true,
    overlay: undefined,
    validation: "Review required",
    conditional: "HR extraction only",
    notes: "Candidate UI and candidate PDF generation must never edit this field",
  },
  {
    id: "official_proceed_to_offer",
    page: 2,
    section: "FOR OFFICIAL USE ONLY",
    label: "Proceed to offer",
    type: "yes_no",
    row: undefined,
    owner: "hr",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "No" },
    exportable: true,
    overlay: undefined,
    validation: "Review required",
    conditional: "HR extraction only",
    notes: "Candidate UI and candidate PDF generation must never edit this field",
  },
  {
    id: "official_employment_type",
    page: 2,
    section: "FOR OFFICIAL USE ONLY",
    label: "Type of employment",
    type: "choice",
    row: undefined,
    owner: "hr",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "No" },
    exportable: true,
    overlay: undefined,
    validation: "Review required",
    conditional: "HR extraction only",
    notes: "Candidate UI and candidate PDF generation must never edit this field",
  },
  {
    id: "official_restaurant_outlet",
    page: 2,
    section: "FOR OFFICIAL USE ONLY",
    label: "Restaurant outlet",
    type: "text",
    row: undefined,
    owner: "hr",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "No" },
    exportable: true,
    overlay: undefined,
    validation: "Review required",
    conditional: "HR extraction only",
    notes: "Candidate UI and candidate PDF generation must never edit this field",
  },
  {
    id: "official_other_remarks",
    page: 2,
    section: "FOR OFFICIAL USE ONLY",
    label: "Other Remarks",
    type: "multiline",
    row: undefined,
    owner: "hr",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "No" },
    exportable: true,
    overlay: undefined,
    validation: "Review required",
    conditional: "HR extraction only",
    notes: "Candidate UI and candidate PDF generation must never edit this field",
  },
  {
    id: "official_commencement_date",
    page: 2,
    section: "FOR OFFICIAL USE ONLY",
    label: "Date of commencement",
    type: "date",
    row: undefined,
    owner: "hr",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "No" },
    exportable: true,
    overlay: undefined,
    validation: "Review required",
    conditional: "HR extraction only",
    notes: "Candidate UI and candidate PDF generation must never edit this field",
  },
  {
    id: "official_job_title",
    page: 2,
    section: "FOR OFFICIAL USE ONLY",
    label: "Job Title",
    type: "text",
    row: undefined,
    owner: "hr",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "No" },
    exportable: true,
    overlay: undefined,
    validation: "Review required",
    conditional: "HR extraction only",
    notes: "Candidate UI and candidate PDF generation must never edit this field",
  },
  {
    id: "official_base_salary_offer",
    page: 2,
    section: "FOR OFFICIAL USE ONLY",
    label: "Base Salary Offer",
    type: "text",
    row: undefined,
    owner: "hr",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "No" },
    exportable: true,
    overlay: undefined,
    validation: "Review required",
    conditional: "HR extraction only",
    notes: "Candidate UI and candidate PDF generation must never edit this field",
  },
  {
    id: "official_other_salary_details",
    page: 2,
    section: "FOR OFFICIAL USE ONLY",
    label: "Other Salary Details",
    type: "text",
    row: undefined,
    owner: "hr",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "No" },
    exportable: true,
    overlay: undefined,
    validation: "Review required",
    conditional: "HR extraction only",
    notes: "Candidate UI and candidate PDF generation must never edit this field",
  },
  {
    id: "official_probation_period",
    page: 2,
    section: "FOR OFFICIAL USE ONLY",
    label: "Probation Period",
    type: "text",
    row: undefined,
    owner: "hr",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "No" },
    exportable: true,
    overlay: undefined,
    validation: "Review required",
    conditional: "HR extraction only",
    notes: "Candidate UI and candidate PDF generation must never edit this field",
  },
  {
    id: "official_other_offer_details",
    page: 2,
    section: "FOR OFFICIAL USE ONLY",
    label: "Other Offer Details",
    type: "multiline",
    row: undefined,
    owner: "hr",
    pocRequired: "optional",
    sources: { resume: "No", linkedin: "No", manual: "No" },
    exportable: true,
    overlay: undefined,
    validation: "Review required",
    conditional: "HR extraction only",
    notes: "Candidate UI and candidate PDF generation must never edit this field",
  },
] as const;
